<?xml version="1.0" encoding="UTF-8" ?>

<!-- ULD 2.7 : Universal Language Dictionary : copyright 2008-2009 R.K.Harrison -->
<!-- * * * revision of 6 October 2009 * * * -->

<!DOCTYPE ULD [
  <!ELEMENT ULD (entry)+ >
  <!ELEMENT entry (number, level, links, English, Deutsch, Nederlands, Italiano, Nihongo, Esperanto, Novial, Tsolyani) >
  <!ELEMENT number (#PCDATA) >
  <!ELEMENT level (#PCDATA) >
  <!ELEMENT links (#PCDATA) >
  <!ELEMENT English (#PCDATA) >
  <!ELEMENT Deutsch (#PCDATA) >
  <!ELEMENT Nederlands (#PCDATA) >
  <!ELEMENT Italiano (#PCDATA) >
  <!ELEMENT Nihongo (#PCDATA) >
  <!ELEMENT Esperanto (#PCDATA) >
  <!ELEMENT Novial (#PCDATA) >
  <!ELEMENT Tsolyani (#PCDATA) >
]>

<ULD>


<!-- chapter 01 -->


<!-- subsection -->

<entry>
<number>0101</number>
<level>0</level>
<links></links>
<English>from (moving out of or away from) [pr] </English>
<Deutsch>von, aus</Deutsch>
<Nederlands>van, vandaan</Nederlands>
<Italiano>da [pr]</Italiano>
<Nihongo></Nihongo>
<Esperanto>de, el</Esperanto>
<Novial>ek, fro</Novial>
<Tsolyani>mik- [pfx]</Tsolyani>
</entry>

<entry>
<number>0102</number>
<level>0</level>
<links></links>
<English>to, towards, at (moving toward) [pr] </English>
<Deutsch>nach, zu</Deutsch>
<Nederlands>naar, tot, tegen</Nederlands>
<Italiano>a [pr]</Italiano>
<Nihongo></Nihongo>
<Esperanto>al</Esperanto>
<Novial>a, vers</Novial>
<Tsolyani>mol- [pfx]</Tsolyani>
</entry>

<entry>
<number>0103</number>
<level>0</level>
<links></links>
<English>at (in the same location as) [pr]</English>
<Deutsch>an, bei</Deutsch>
<Nederlands>te, bij, op</Nederlands>
<Italiano>a [pr]</Italiano>
<Nihongo></Nihongo>
<Esperanto>ĉe</Esperanto>
<Novial>an, che</Novial>
<Tsolyani>tham- [pfx]</Tsolyani>
</entry>


<!-- subsection -->

<entry>
<number>0110</number>
<level>0</level>
<links></links>
<English>in (located inside of) [pr] </English>
<Deutsch>in</Deutsch>
<Nederlands>in</Nederlands>
<Italiano>in</Italiano>
<Nihongo></Nihongo>
<Esperanto>en</Esperanto>
<Novial>in</Novial>
<Tsolyani>bru- [pfx]</Tsolyani>
</entry>

<entry>
<number>0111</number>
<level>1</level>
<links></links>
<English>outside of, exterior to [pr] </English>
<Deutsch>aussen</Deutsch>
<Nederlands>buiten</Nederlands>
<Italiano>fuori di [pr]</Italiano>
<Nihongo></Nihongo>
<Esperanto>ekster</Esperanto>
<Novial>exter</Novial>
<Tsolyani>tsíre- [pfx], tsíren</Tsolyani>
</entry>


<!-- subsection -->

<entry>
<number>0120</number>
<level>1</level>
<links></links>
<English>above, over [pr]</English>
<Deutsch>über</Deutsch>
<Nederlands>over, boven</Nederlands>
<Italiano>su, sopra a [pr]</Italiano>
<Nihongo></Nihongo>
<Esperanto>super</Esperanto>
<Novial>super</Novial>
<Tsolyani>som- [pfx]</Tsolyani>
</entry>

<entry>
<number>0121</number>
<level>1</level>
<links></links>
<English>under, below, beneath [pr] </English>
<Deutsch>unter</Deutsch>
<Nederlands>onder</Nederlands>
<Italiano>sotto [pr]</Italiano>
<Nihongo></Nihongo>
<Esperanto>sub</Esperanto>
<Novial>sub</Novial>
<Tsolyani>dhu- [pfx]</Tsolyani>
</entry>


<!-- subsection -->

<entry>
<number>0130</number>
<level>1</level>
<links></links>
<English>in front of, ahead of, before (spatially) [pr] </English>
<Deutsch>vor</Deutsch>
<Nederlands>voor</Nederlands>
<Italiano>davanti a [pr]</Italiano>
<Nihongo></Nihongo>
<Esperanto>antaŭ</Esperanto>
<Novial>devan</Novial>
<Tsolyani>gureng- [pfx]</Tsolyani>
</entry>

<entry>
<number>0131</number>
<level>1</level>
<links></links>
<English>behind, in back of, to the rear of [pr] </English>
<Deutsch>hinter</Deutsch>
<Nederlands>achter</Nederlands>
<Italiano>dietro a [pr]</Italiano>
<Nihongo></Nihongo>
<Esperanto>malantaŭ</Esperanto>
<Novial>hinter</Novial>
<Tsolyani>dhi- [pfx]</Tsolyani>
</entry>


<!-- subsection -->

<entry>
<number>0140</number>
<level>1</level>
<links></links>
<English>before, prior to, earlier than [pr]</English>
<Deutsch>vor</Deutsch>
<Nederlands>voor [pr], eer {archaic}</Nederlands>
<Italiano>prima di [pr]</Italiano>
<Nihongo></Nihongo>
<Esperanto>antaŭ</Esperanto>
<Novial>ante</Novial>
<Tsolyani>che- [pfx]</Tsolyani>
</entry>

<entry>
<number>0141</number>
<level>1</level>
<links></links>
<English>during [pr] </English>
<Deutsch>während</Deutsch>
<Nederlands>tijdens, gedurende</Nederlands>
<Italiano>durante [pr]</Italiano>
<Nihongo></Nihongo>
<Esperanto>dum [pr/cj]</Esperanto>
<Novial>durant</Novial>
<Tsolyani>bru- [pfx]</Tsolyani>
</entry>

<entry>
<number>0142</number>
<level>1</level>
<links></links>
<English>after (later than; in the future of) [pr]</English>
<Deutsch>nach</Deutsch>
<Nederlands>na [pr]</Nederlands>
<Italiano>dopo [pr]</Italiano>
<Nihongo></Nihongo>
<Esperanto>post </Esperanto>
<Novial>after</Novial>
<Tsolyani>tu- [pfx], t˙n [cj]</Tsolyani>
</entry>


<!-- subsection -->

<entry>
<number>0150</number>
<level>0</level>
<links></links>
<English>with (accompanied by / furnished with) [pr] </English>
<Deutsch>mit</Deutsch>
<Nederlands>met, bij</Nederlands>
<Italiano>con [pr]</Italiano>
<Nihongo></Nihongo>
<Esperanto>kun</Esperanto>
<Novial>kun</Novial>
<Tsolyani>pag- [pfx]</Tsolyani>
</entry>

<entry>
<number>0151</number>
<level>1</level>
<links></links>
<English>without (not with) [pr]</English>
<Deutsch>ohne</Deutsch>
<Nederlands>zonder</Nederlands>
<Italiano>senza [pr]</Italiano>
<Nihongo></Nihongo>
<Esperanto>sen</Esperanto>
<Novial>sin</Novial>
<Tsolyani>ye- [pfx]</Tsolyani>
</entry>


<!-- subsection -->

<entry>
<number>0160</number>
<level>1</level>
<links></links>
<English>around, encircling, surrounding [pr] </English>
<Deutsch>rund um</Deutsch>
<Nederlands>rond, rondom, om</Nederlands>
<Italiano>attorno a [pr]</Italiano>
<Nihongo></Nihongo>
<Esperanto>ĉirkaŭ</Esperanto>
<Novial>sirk</Novial>
<Tsolyani>bim- [pfx]</Tsolyani>
</entry>

<entry>
<number>0161</number>
<level>1</level>
<links></links>
<English>between, among [pr] </English>
<Deutsch>zwischen</Deutsch>
<Nederlands>tussen, inter-</Nederlands>
<Italiano>tra, fra [pr]</Italiano>
<Nihongo></Nihongo>
<Esperanto>inter</Esperanto>
<Novial>inter</Novial>
<Tsolyani>dai- [pfx] {repeated: between X and Y is "dai-X dai-Y"}</Tsolyani>
</entry>

<entry>
<number>0162</number>
<level>1</level>
<links></links>
<English>beyond, farther than, exceeding [pr] </English>
<Deutsch>jenseits von</Deutsch>
<Nederlands>verder dan, voorbij</Nederlands>
<Italiano>oltre [pr]</Italiano>
<Nihongo></Nihongo>
<Esperanto>preter</Esperanto>
<Novial>trans</Novial>
<Tsolyani>jézu mik- [pfx]</Tsolyani>
</entry>

<entry>
<number>0163</number>
<level>1</level>
<links></links>
<English>near, close to [pr] </English>
<Deutsch>nahe, bei</Deutsch>
<Nederlands>dichtbij, nabij</Nederlands>
<Italiano>vicino a [pr]</Italiano>
<Nihongo></Nihongo>
<Esperanto>proksime al</Esperanto>
<Novial>proxim</Novial>
<Tsolyani>hats- [pfx], hatsÌlin [pr]</Tsolyani>
</entry>

<entry>
<number>0164</number>
<level>1</level>
<links></links>
<English>on (resting on; touching the top or other surface of) [pr]</English>
<Deutsch>auf</Deutsch>
<Nederlands>op</Nederlands>
<Italiano>su [pr]</Italiano>
<Nihongo></Nihongo>
<Esperanto>sur</Esperanto>
<Novial>sur</Novial>
<Tsolyani>som- [pfx]</Tsolyani>
</entry>

<entry>
<number>0165</number>
<level>1</level>
<links></links>
<English>across (at the other side of; to the other side of) [pr]</English>
<Deutsch>quer über, jenseits</Deutsch>
<Nederlands>over</Nederlands>
<Italiano>al di là, oltre [pr]</Italiano>
<Nihongo></Nihongo>
<Esperanto>trans</Esperanto>
<Novial>tra (across, through), trans (on the other side of)</Novial>
<Tsolyani>pas- [pfx]</Tsolyani>
</entry>

<entry>
<number>0166</number>
<level>1</level>
<links></links>
<English>through [pr]</English>
<Deutsch>durch</Deutsch>
<Nederlands>door</Nederlands>
<Italiano>attraverso, per [pr]</Italiano>
<Nihongo></Nihongo>
<Esperanto>tra</Esperanto>
<Novial>tra</Novial>
<Tsolyani>ti- [pfx]</Tsolyani>
</entry>


<!-- subsection -->

<entry>
<number>0170</number>
<level>1</level>
<links></links>
<English>about (pertaining to; on the topic of) [pr]</English>
<Deutsch>über</Deutsch>
<Nederlands>betreffende, over</Nederlands>
<Italiano>a proposito di [pr]</Italiano>
<Nihongo></Nihongo>
<Esperanto>pri</Esperanto>
<Novial>pri</Novial>
<Tsolyani>jil- [pfx]</Tsolyani>
</entry>

<entry>
<number>0171</number>
<level>1</level>
<links></links>
<English>because of, due to [pr] </English>
<Deutsch>wegen</Deutsch>
<Nederlands>wegens</Nederlands>
<Italiano>a causa di [pr]</Italiano>
<Nihongo></Nihongo>
<Esperanto>pro, kaŭze de</Esperanto>
<Novial>pro</Novial>
<Tsolyani>chiwài- [pfx]</Tsolyani>
</entry>

<entry>
<number>0172</number>
<level>0</level>
<links></links>
<English>by means of, via, per, with (using; through instrumentality of) [pr]</English>
<Deutsch>mit, mittels, vermittels, durch</Deutsch>
<Nederlands>met, met behulp van, door middel van</Nederlands>
<Italiano>con, tramite [pr]</Italiano>
<Nihongo></Nihongo>
<Esperanto>per</Esperanto>
<Novial>per</Novial>
<Tsolyani>-lu [? sfx]</Tsolyani>
</entry>

<entry>
<number>0173</number>
<level>1</level>
<links></links>
<English>except for, apart from, excluding [pr] </English>
<Deutsch>abgesehen von, ausgenommen</Deutsch>
<Nederlands>behalve, afgezien van</Nederlands>
<Italiano>tranne [pr]</Italiano>
<Nihongo></Nihongo>
<Esperanto>krom</Esperanto>
<Novial>exept</Novial>
<Tsolyani>yáun- [pfx]</Tsolyani>
</entry>

<entry>
<number>0174</number>
<level>0</level>
<links></links>
<English>for (to benefit; destined for; for the purpose of) [pr] </English>
<Deutsch>für</Deutsch>
<Nederlands>voor, ten behoeve van</Nederlands>
<Italiano>per [pr]</Italiano>
<Nihongo></Nihongo>
<Esperanto>por</Esperanto>
<Novial>por</Novial>
<Tsolyani>chalu- [pfx]</Tsolyani>
</entry>

<entry>
<number>0175</number>
<level>1</level>
<links></links>
<English>for (in exchange for) [pr] </English>
<Deutsch>für, in austausch für</Deutsch>
<Nederlands>voor</Nederlands>
<Italiano>per [pr]</Italiano>
<Nihongo></Nihongo>
<Esperanto>por, kontraŭ</Esperanto>
<Novial>po</Novial>
<Tsolyani>tla- ... bru- [pfx: to exchange X for Y = tla-X bru-Y]</Tsolyani>
</entry>

<entry>
<number>0176</number>
<level>1</level>
<links></links>
<English>instead of, rather than [pr] </English>
<Deutsch>anstatt</Deutsch>
<Nederlands>in plaats van</Nederlands>
<Italiano>invece di, più di [pr]</Italiano>
<Nihongo></Nihongo>
<Esperanto>anstataŭ </Esperanto>
<Novial>insted</Novial>
<Tsolyani>kar- [pfx]</Tsolyani>
</entry>

<entry>
<number>0177</number>
<level>1</level>
<links></links>
<English>like, similar to [pr] </English>
<Deutsch>wie, gleich</Deutsch>
<Nederlands>als, gelijk an</Nederlands>
<Italiano>come [pr]</Italiano>
<Nihongo></Nihongo>
<Esperanto>simila al</Esperanto>
<Novial>simil ad, samiman kam</Novial>
<Tsolyani>ssyi- [pfx]</Tsolyani>
</entry>

<entry>
<number>0178</number>
<level>0</level>
<links></links>
<English>of (belonging to; associated with; = genitive) [pr] </English>
<Deutsch>von, [Genitiv]</Deutsch>
<Nederlands>van</Nederlands>
<Italiano>di [pr]</Italiano>
<Nihongo></Nihongo>
<Esperanto>de</Esperanto>
<Novial>de</Novial>
<Tsolyani>hi- [pfx = "associated with"], -mra [sfx = "owned by"]</Tsolyani>
</entry>

<entry>
<number>0179</number>
<level>1</level>
<links></links>
<English>of (containing the measured quantity: "two liters of water") [pr]</English>
<Deutsch>von</Deutsch>
<Nederlands>met</Nederlands>
<Italiano>di [pr]</Italiano>
<Nihongo></Nihongo>
<Esperanto>da</Esperanto>
<Novial>de</Novial>
<Tsolyani></Tsolyani>
</entry>

<entry>
<number>0180</number>
<level>0</level>
<links></links>
<English>than, compared to [pr/cj] </English>
<Deutsch>als, im Vergleich zu</Deutsch>
<Nederlands>dan</Nederlands>
<Italiano>di [pr]</Italiano>
<Nihongo></Nihongo>
<Esperanto>ol [cj]</Esperanto>
<Novial>kam</Novial>
<Tsolyani></Tsolyani>
</entry>


<!-- end of chapter -->

<!-- chapter 02 -->


<!-- subsection -->

<entry>
<number>0201</number>
<level>0</level>
<links></links>
<English>be (predicative copula as in "I am a man") [v]</English>
<Deutsch>sein</Deutsch>
<Nederlands>zijn</Nederlands>
<Italiano>essere [v]</Italiano>
<Nihongo></Nihongo>
<Esperanto>esti</Esperanto>
<Novial>es</Novial>
<Tsolyani>guál</Tsolyani>
</entry>

<entry>
<number>0202</number>
<level>0</level>
<links></links>
<English>exist [v]</English>
<Deutsch>existieren</Deutsch>
<Nederlands>bestaan</Nederlands>
<Italiano>esserci, esistere [v]</Italiano>
<Nihongo></Nihongo>
<Esperanto>ekzisti</Esperanto>
<Novial>exist</Novial>
<Tsolyani>guál</Tsolyani>
</entry>

<entry>
<number>0203</number>
<level>0</level>
<links></links>
<English>become (begin to be; acquire the quality...) [v]</English>
<Deutsch>werden</Deutsch>
<Nederlands>worden</Nederlands>
<Italiano>diventare [v]</Italiano>
<Nihongo></Nihongo>
<Esperanto>iĝi</Esperanto>
<Novial>deveni</Novial>
<Tsolyani>guál, nrí (to change from X to Y: guál X, nrí Y)</Tsolyani>
</entry>

<entry>
<number>0204</number>
<level>0</level>
<links></links>
<English>cause (induce something to be/happen) [v]</English>
<Deutsch>verursachen</Deutsch>
<Nederlands>veroorzaken</Nederlands>
<Italiano>fare [aux v], causare [v]</Italiano>
<Nihongo></Nihongo>
<Esperanto>kaŭzi</Esperanto>
<Novial>fika</Novial>
<Tsolyani>nonrí</Tsolyani>
</entry>

<entry>
<number>0205</number>
<level>0</level>
<links></links>
<English>make, render (impart quality X to Y; e.g. "I make you happy") [v]</English>
<Deutsch>machen</Deutsch>
<Nederlands>maken</Nederlands>
<Italiano>fare, rendere [v]</Italiano>
<Nihongo></Nihongo>
<Esperanto>igi</Esperanto>
<Novial>fika</Novial>
<Tsolyani>vu- [pfx] (?)</Tsolyani>
</entry>

<entry>
<number>0206</number>
<level>0</level>
<links></links>
<English>do, perform, engage in (specified activity) [v]</English>
<Deutsch>machen, tun</Deutsch>
<Nederlands>doen</Nederlands>
<Italiano>fare [v]</Italiano>
<Nihongo></Nihongo>
<Esperanto>fari</Esperanto>
<Novial>fa</Novial>
<Tsolyani>moyí</Tsolyani>
</entry>

<entry>
<number>0207</number>
<level>0</level>
<links></links>
<English>have (possess / be furnished with) [v]</English>
<Deutsch>haben</Deutsch>
<Nederlands>hebben, bezitten</Nederlands>
<Italiano>avere [v]</Italiano>
<Nihongo></Nihongo>
<Esperanto>havi, posedi</Esperanto>
<Novial>have</Novial>
<Tsolyani>mén</Tsolyani>
</entry>

<entry>
<number>0208</number>
<level>0</level>
<links></links>
<English>can (is/are able to ...) [aux v]</English>
<Deutsch>können</Deutsch>
<Nederlands>kunnen</Nederlands>
<Italiano>potere [aux v]</Italiano>
<Nihongo></Nihongo>
<Esperanto>povas</Esperanto>
<Novial>pove</Novial>
<Tsolyani>tlayésh</Tsolyani>
</entry>

<entry>
<number>0209</number>
<level>0</level>
<links></links>
<English>should, ought to (is/are expected/advised to ...) [aux v]</English>
<Deutsch>sollen</Deutsch>
<Nederlands>moeten, behoren, horen</Nederlands>
<Italiano>dovere [aux v]</Italiano>
<Nihongo></Nihongo>
<Esperanto>devus</Esperanto>
<Novial>deve</Novial>
<Tsolyani>zhé</Tsolyani>
</entry>


<!-- subsection -->

<entry>
<number>0220</number>
<level>0</level>
<links></links>
<English>this (demonstrative) [aj/pn]</English>
<Deutsch>diese [f], dieser [m], dieses [nt]</Deutsch>
<Nederlands>deze [masc/fem], dit [nt]</Nederlands>
<Italiano>questo [aj/pn]</Italiano>
<Nihongo></Nihongo>
<Esperanto>ĉi tiu</Esperanto>
<Novial>disi [aj], diso, -a, -e [pn]</Novial>
<Tsolyani>másun, máisur, komáisur,... (class dist. for persons; also object)</Tsolyani>
</entry>

<entry>
<number>0221</number>
<level>0</level>
<links></links>
<English>that (demonstrative) [aj/pn]</English>
<Deutsch>das</Deutsch>
<Nederlands>dat [nt], die [f/m]</Nederlands>
<Italiano>quello [aj/pn]</Italiano>
<Nihongo></Nihongo>
<Esperanto>tiu</Esperanto>
<Novial>ti [aj], to, ta, te [pn]</Novial>
<Tsolyani>másunònul, máisurònul,... (class dist. for persons; also object)</Tsolyani>
</entry>

<entry>
<number>0222</number>
<level>1</level>
<links></links>
<English>any (no particular one of) [aj]</English>
<Deutsch>irgendeiner</Deutsch>
<Nederlands>enig, ieder</Nederlands>
<Italiano>tutti [plural aj]</Italiano>
<Nihongo></Nihongo>
<Esperanto>ajna, iu ajn</Esperanto>
<Novial>irgi</Novial>
<Tsolyani>hlòn- [quantifier pfx], hlónin [adj]</Tsolyani>
</entry>

<entry>
<number>0223</number>
<level>1</level>
<links></links>
<English>each, every [aj]</English>
<Deutsch>jeder</Deutsch>
<Nederlands>ieder, elk</Nederlands>
<Italiano>ogni [aj]</Italiano>
<Nihongo></Nihongo>
<Esperanto>ĉiu</Esperanto>
<Novial>chaki</Novial>
<Tsolyani>hlónilin [adj], hlònil- [quantifier pfx]</Tsolyani>
</entry>

<entry>
<number>0224</number>
<level>1</level>
<links></links>
<English>what? (which thing out of several?), which? [aj]</English>
<Deutsch>was, welch</Deutsch>
<Nederlands>wat, welke</Nederlands>
<Italiano>che, quale</Italiano>
<Nihongo></Nihongo>
<Esperanto>kio, kiu</Esperanto>
<Novial></Novial>
<Tsolyani>zhúr</Tsolyani>
</entry>

<entry>
<number>0225</number>
<level>0</level>
<links></links>
<English>no (not any; not even one of) [aj]</English>
<Deutsch></Deutsch>
<Nederlands></Nederlands>
<Italiano></Italiano>
<Nihongo></Nihongo>
<Esperanto></Esperanto>
<Novial></Novial>
<Tsolyani></Tsolyani>
</entry>


<!-- subsection -->

<entry>
<number>0230</number>
<level>0</level>
<links></links>
<English>and [cj]</English>
<Deutsch>und</Deutsch>
<Nederlands>en</Nederlands>
<Italiano>e [cj]</Italiano>
<Nihongo></Nihongo>
<Esperanto>kaj</Esperanto>
<Novial>e</Novial>
<Tsolyani>lél</Tsolyani>
</entry>

<entry>
<number>0231</number>
<level>1</level>
<links></links>
<English>but, however [cj]</English>
<Deutsch>aber, jedoch</Deutsch>
<Nederlands>maar</Nederlands>
<Italiano>ma [cj]</Italiano>
<Nihongo></Nihongo>
<Esperanto>sed</Esperanto>
<Novial>ma</Novial>
<Tsolyani>málel</Tsolyani>
</entry>

<entry>
<number>0232</number>
<level>0</level>
<links></links>
<English>if (on condition that...; supposing that...) [cj]</English>
<Deutsch>wenn, falls</Deutsch>
<Nederlands>als, indien</Nederlands>
<Italiano>se [cj]</Italiano>
<Nihongo></Nihongo>
<Esperanto>se</Esperanto>
<Novial>si</Novial>
<Tsolyani>vá (possible condition), grúmir (impossible condition)</Tsolyani>
</entry>

<entry>
<number>0233</number>
<level>0</level>
<links></links>
<English>or [cj]</English>
<Deutsch>oder</Deutsch>
<Nederlands>of</Nederlands>
<Italiano>o [cj], oppure [cj]</Italiano>
<Nihongo></Nihongo>
<Esperanto>aŭ</Esperanto>
<Novial>o</Novial>
<Tsolyani>ra... ra ... (either X or Y)</Tsolyani>
</entry>

<entry>
<number>0234</number>
<level>1</level>
<links></links>
<English>that (e.g. "I know that you are right") [cj]</English>
<Deutsch>dass</Deutsch>
<Nederlands>dat</Nederlands>
<Italiano>che [cj]</Italiano>
<Nihongo></Nihongo>
<Esperanto>ke</Esperanto>
<Novial>ke</Novial>
<Tsolyani>pár</Tsolyani>
</entry>


<!-- subsection -->

<entry>
<number>0240</number>
<level>1</level>
<links></links>
<English>also, too [av]</English>
<Deutsch>auch</Deutsch>
<Nederlands>ook</Nederlands>
<Italiano>anche [av]</Italiano>
<Nihongo></Nihongo>
<Esperanto>ankaŭ</Esperanto>
<Novial>anke</Novial>
<Tsolyani>tatlán</Tsolyani>
</entry>

<entry>
<number>0241</number>
<level>1</level>
<links></links>
<English>maybe, perhaps [av]</English>
<Deutsch>vielleicht</Deutsch>
<Nederlands>misschien, mogelijk</Nederlands>
<Italiano>forse [av]</Italiano>
<Nihongo></Nihongo>
<Esperanto>eble</Esperanto>
<Novial>forsan, poves</Novial>
<Tsolyani>srán</Tsolyani>
</entry>

<entry>
<number>0242</number>
<level>0</level>
<links></links>
<English>not [av]</English>
<Deutsch>nicht</Deutsch>
<Nederlands>niet</Nederlands>
<Italiano>non [av]</Italiano>
<Nihongo></Nihongo>
<Esperanto>ne</Esperanto>
<Novial>non</Novial>
<Tsolyani>thá (future, cond., imperative), yá (present, past)</Tsolyani>
</entry>

<entry>
<number>0243</number>
<level>1</level>
<links></links>
<English>only (exclusively or "solitarily"), solely [av]</English>
<Deutsch>nur</Deutsch>
<Nederlands>alleen</Nederlands>
<Italiano>solo, solamente [av]</Italiano>
<Nihongo></Nihongo>
<Esperanto>sole</Esperanto>
<Novial>solim</Novial>
<Tsolyani>prushén</Tsolyani>
</entry>


<!-- subsection -->

<entry>
<number>0250</number>
<level>1</level>
<links></links>
<English>here (in/to this place) [av]</English>
<Deutsch>hier</Deutsch>
<Nederlands>hier</Nederlands>
<Italiano>qui [av]</Italiano>
<Nihongo></Nihongo>
<Esperanto>ĉi tie, ĉi tien</Esperanto>
<Novial>hir, dislok</Novial>
<Tsolyani>dáhlte</Tsolyani>
</entry>

<entry>
<number>0251</number>
<level>1</level>
<links></links>
<English>there (at/to that place) [av]</English>
<Deutsch>da, dort</Deutsch>
<Nederlands>daar</Nederlands>
<Italiano>là [av]</Italiano>
<Nihongo></Nihongo>
<Esperanto>tie, tien</Esperanto>
<Novial>dar, tilok</Novial>
<Tsolyani>onótl, onétl (Eastern)</Tsolyani>
</entry>

<entry>
<number>0252</number>
<level>1</level>
<links></links>
<English>where? (at/to what place?) [av]</English>
<Deutsch>wo</Deutsch>
<Nederlands>waar</Nederlands>
<Italiano>dove [av]</Italiano>
<Nihongo></Nihongo>
<Esperanto>kie, kien</Esperanto>
<Novial>vor</Novial>
<Tsolyani>fénul</Tsolyani>
</entry>


<!-- subsection -->

<entry>
<number>0260</number>
<level>1</level>
<links></links>
<English>how? (in what manner?) [av]</English>
<Deutsch>wie</Deutsch>
<Nederlands>hoe</Nederlands>
<Italiano>come [av]</Italiano>
<Nihongo></Nihongo>
<Esperanto>kiel</Esperanto>
<Novial></Novial>
<Tsolyani>ssúmim</Tsolyani>
</entry>

<entry>
<number>0261</number>
<level>1</level>
<links></links>
<English>when? (at what time?) [av]</English>
<Deutsch>wann</Deutsch>
<Nederlands>wanneer</Nederlands>
<Italiano>quando [av]</Italiano>
<Nihongo></Nihongo>
<Esperanto>kiam</Esperanto>
<Novial>quand</Novial>
<Tsolyani>marakál</Tsolyani>
</entry>

<entry>
<number>0262</number>
<level>1</level>
<links></links>
<English>why? (for what reason?) [av]</English>
<Deutsch>warum, wieso, weshalb</Deutsch>
<Nederlands>waarom</Nederlands>
<Italiano>perchè [av]</Italiano>
<Nihongo></Nihongo>
<Esperanto>kial</Esperanto>
<Novial>pro quum {?}</Novial>
<Tsolyani>dépu</Tsolyani>
</entry>


<!-- subsection -->

<entry>
<number>0270</number>
<level>2</level>
<links></links>
<English>[さん in Japanese; no English equivalent]</English>
<Deutsch>[no equivalent]</Deutsch>
<Nederlands>[no equivalent]</Nederlands>
<Italiano>[no equivalent]</Italiano>
<Nihongo></Nihongo>
<Esperanto>[no equivalent]</Esperanto>
<Novial>[no equivalent]</Novial>
<Tsolyani>[no equivalent]</Tsolyani>
</entry>

<entry>
<number>0271</number>
<level>2</level>
<links></links>
<English>Mister, Mr.</English>
<Deutsch>Herr</Deutsch>
<Nederlands>meneer</Nederlands>
<Italiano>Sig.</Italiano>
<Nihongo></Nihongo>
<Esperanto>sinjoro</Esperanto>
<Novial>Sinioro</Novial>
<Tsolyani></Tsolyani>
</entry>

<entry>
<number>0272</number>
<level>2</level>
<links></links>
<English>Ms., Miss/Mrs.</English>
<Deutsch>[no equivalent]</Deutsch>
<Nederlands>[no equivalent]</Nederlands>
<Italiano>[no equivalent]</Italiano>
<Nihongo></Nihongo>
<Esperanto>[no equivalent]</Esperanto>
<Novial>[no equivalent]</Novial>
<Tsolyani></Tsolyani>
</entry>

<entry>
<number>0273</number>
<level>2</level>
<links></links>
<English>Miss</English>
<Deutsch>Fraülein, Frau (many women prefer the more neutral 'Frau')</Deutsch>
<Nederlands>juffrouw</Nederlands>
<Italiano>Sig.na</Italiano>
<Nihongo></Nihongo>
<Esperanto>fraŭlino</Esperanto>
<Novial>Damsela, Siniorina</Novial>
<Tsolyani></Tsolyani>
</entry>

<entry>
<number>0274</number>
<level>2</level>
<links></links>
<English>Mrs.</English>
<Deutsch>Frau</Deutsch>
<Nederlands>Mevrouw</Nederlands>
<Italiano>Sig.ra</Italiano>
<Nihongo></Nihongo>
<Esperanto>sinjorino</Esperanto>
<Novial>Siniora</Novial>
<Tsolyani></Tsolyani>
</entry>


<!-- subsection -->

<entry>
<number>0280</number>
<level>0</level>
<links></links>
<English>that [relative] (as in "study the language that appeals to you")</English>
<Deutsch>der, die, das</Deutsch>
<Nederlands>die, dat</Nederlands>
<Italiano>che</Italiano>
<Nihongo></Nihongo>
<Esperanto>kiu [nom.sing], kiuj [nom.plur], kiun [acc.sing], kiujn [acc.plur]</Esperanto>
<Novial>kel</Novial>
<Tsolyani>[no equivalent]</Tsolyani>
</entry>

<entry>
<number>0281</number>
<level>0</level>
<links></links>
<English>I [nom], me [acc]</English>
<Deutsch>ich [nom], mich [acc], mir [dat]</Deutsch>
<Nederlands>ik, mij</Nederlands>
<Italiano>io, mi, me</Italiano>
<Nihongo></Nihongo>
<Esperanto>mi [nom], min [acc]</Esperanto>
<Novial>me</Novial>
<Tsolyani>lín, lú, lúm, lukán, salúm, kosalúm</Tsolyani>
</entry>

<entry>
<number>0282</number>
<level>0</level>
<links></links>
<English>you [singular]</English>
<Deutsch>du [nom.plain], dich [acc.plain], dir [dat.plain], Sie [polite]</Deutsch>
<Nederlands>jij, je [plain], u [polite]</Nederlands>
<Italiano>tu [nom.plain], lei [polite]</Italiano>
<Nihongo></Nihongo>
<Esperanto>vi [nom], vin [acc]</Esperanto>
<Novial>vu</Novial>
<Tsolyani>tsám, túsmi, túsmidàli, mìsritúsmidàli</Tsolyani>
</entry>

<!-- htmlx I urge you to read the Notes for this chapter. -->

<!-- end of chapter -->


<!-- chapter 03 -->


<!-- subsection -->

<entry>
<number>0301</number>
<level>1</level>
<links></links>
<English>human being, person (any living member of Homo sapiens)</English>
<Deutsch>Mensch, Person</Deutsch>
<Nederlands>mens</Nederlands>
<Italiano>persona, essere umano</Italiano>
<Nihongo></Nihongo>
<Esperanto>homo</Esperanto>
<Novial>home</Novial>
<Tsolyani>tsólukoi (noble), tsólukh (ignoble), moláikoi (noble non-human), etc.</Tsolyani>
</entry>

<entry>
<number>0303</number>
<level>1</level>
<links></links>
<English>baby</English>
<Deutsch>Kind, Baby</Deutsch>
<Nederlands>zuigeling</Nederlands>
<Italiano>bambino</Italiano>
<Nihongo></Nihongo>
<Esperanto>bebo</Esperanto>
<Novial>infante (-o, -a)</Novial>
<Tsolyani>alánikh</Tsolyani>
</entry>

<entry>
<number>0305</number>
<level>1</level>
<links></links>
<English>child</English>
<Deutsch>Kind</Deutsch>
<Nederlands>kind</Nederlands>
<Italiano>bambino</Italiano>
<Nihongo></Nihongo>
<Esperanto>infano</Esperanto>
<Novial></Novial>
<Tsolyani>bünúkh</Tsolyani>
</entry>

<entry>
<number>0307</number>
<level>1</level>
<links></links>
<English>boy</English>
<Deutsch>Junge</Deutsch>
<Nederlands>jongen</Nederlands>
<Italiano>ragazzo</Italiano>
<Nihongo></Nihongo>
<Esperanto>knabo</Esperanto>
<Novial>puero</Novial>
<Tsolyani></Tsolyani>
</entry>

<entry>
<number>0309</number>
<level>1</level>
<links></links>
<English>girl</English>
<Deutsch>Mädchen</Deutsch>
<Nederlands>meisje</Nederlands>
<Italiano>ragazza</Italiano>
<Nihongo></Nihongo>
<Esperanto>knabino</Esperanto>
<Novial>puera</Novial>
<Tsolyani>thiálakh</Tsolyani>
</entry>

<entry>
<number>0312</number>
<level>2</level>
<links></links>
<English>adult</English>
<Deutsch>Erwachsene [f], Erwachsener [m]</Deutsch>
<Nederlands>volwassene</Nederlands>
<Italiano>adulto</Italiano>
<Nihongo></Nihongo>
<Esperanto>plenkreskulo</Esperanto>
<Novial></Novial>
<Tsolyani></Tsolyani>
</entry>

<entry>
<number>0314</number>
<level>1</level>
<links></links>
<English>man (adult male person)</English>
<Deutsch>Mann</Deutsch>
<Nederlands>man</Nederlands>
<Italiano>uomo, maschio</Italiano>
<Nihongo></Nihongo>
<Esperanto>viro</Esperanto>
<Novial>homo</Novial>
<Tsolyani>básrimkoi</Tsolyani>
</entry>

<entry>
<number>0316</number>
<level>1</level>
<links></links>
<English>woman (adult female person)</English>
<Deutsch>Frau</Deutsch>
<Nederlands>vrouw</Nederlands>
<Italiano>donna, femmina</Italiano>
<Nihongo></Nihongo>
<Esperanto>virino</Esperanto>
<Novial>homa, fema</Novial>
<Tsolyani>ssánakh (ignoble), hmédhikh (noble), aridánikoi (warrior or indep.)</Tsolyani>
</entry>


<!-- subsection -->

<entry>
<number>0320</number>
<level>2</level>
<links></links>
<English>family</English>
<Deutsch>Familie</Deutsch>
<Nederlands>familie</Nederlands>
<Italiano>famiglia</Italiano>
<Nihongo></Nihongo>
<Esperanto>familio</Esperanto>
<Novial>familie</Novial>
<Tsolyani>héssi-kh</Tsolyani>
</entry>

<entry>
<number>0322</number>
<level>1</level>
<links></links>
<English>father</English>
<Deutsch>Vater</Deutsch>
<Nederlands>vader</Nederlands>
<Italiano>padre</Italiano>
<Nihongo></Nihongo>
<Esperanto>patro</Esperanto>
<Novial>patro</Novial>
<Tsolyani>mrishkánkoi</Tsolyani>
</entry>

<entry>
<number>0324</number>
<level>1</level>
<links></links>
<English>mother</English>
<Deutsch>Mutter</Deutsch>
<Nederlands>moeder</Nederlands>
<Italiano>madre</Italiano>
<Nihongo></Nihongo>
<Esperanto>patrino</Esperanto>
<Novial>matra</Novial>
<Tsolyani>ánukoi</Tsolyani>
</entry>

<entry>
<number>0330</number>
<level>2</level>
<links></links>
<English>grandfather</English>
<Deutsch>Großvater</Deutsch>
<Nederlands>grootvader</Nederlands>
<Italiano>nonno</Italiano>
<Nihongo></Nihongo>
<Esperanto>avo</Esperanto>
<Novial></Novial>
<Tsolyani></Tsolyani>
</entry>

<entry>
<number>0335</number>
<level>2</level>
<links></links>
<English>grandmother</English>
<Deutsch>Großmutter</Deutsch>
<Nederlands>grootmoeder</Nederlands>
<Italiano>nonna</Italiano>
<Nihongo></Nihongo>
<Esperanto>avino</Esperanto>
<Novial></Novial>
<Tsolyani></Tsolyani>
</entry>

<entry>
<number>0340</number>
<level>2</level>
<links></links>
<English>uncle</English>
<Deutsch>Onkel</Deutsch>
<Nederlands>oom</Nederlands>
<Italiano>zio</Italiano>
<Nihongo></Nihongo>
<Esperanto>onklo</Esperanto>
<Novial></Novial>
<Tsolyani></Tsolyani>
</entry>

<entry>
<number>0345</number>
<level>2</level>
<links></links>
<English>aunt</English>
<Deutsch>Tante</Deutsch>
<Nederlands>tante</Nederlands>
<Italiano>zia</Italiano>
<Nihongo></Nihongo>
<Esperanto>onklino</Esperanto>
<Novial></Novial>
<Tsolyani></Tsolyani>
</entry>

<entry>
<number>0350</number>
<level>2</level>
<links></links>
<English>son</English>
<Deutsch>Sohn</Deutsch>
<Nederlands>zoon</Nederlands>
<Italiano>figlio</Italiano>
<Nihongo></Nihongo>
<Esperanto>filo</Esperanto>
<Novial>filio</Novial>
<Tsolyani>ngémukh</Tsolyani>
</entry>

<entry>
<number>0352</number>
<level>2</level>
<links></links>
<English>daughter</English>
<Deutsch>Tochter</Deutsch>
<Nederlands>dochter</Nederlands>
<Italiano>figlia</Italiano>
<Nihongo></Nihongo>
<Esperanto>filino</Esperanto>
<Novial>filia</Novial>
<Tsolyani>ngésakh</Tsolyani>
</entry>

<entry>